import json
import os

import numpy as np
import pandas as pd

try:
    import yfinance as yf
except ImportError:  # pragma: no cover
    raise SystemExit("yfinance not installed. Run: pip install yfinance")


# Curated universe ----------------------------------------------------------- #
BENCHMARK = "SPY"
SECTORS = ["XLK", "XLF", "XLE", "XLV", "XLY", "XLI", "XLP", "XLU", "XLB", "XLRE", "XLC"]
PAIRS = [["KO", "PEP"], ["GLD", "GDX"], ["EWA", "EWC"]]
PAIR_MEMBERS = sorted({t for p in PAIRS for t in p})

TICKERS = sorted(set([BENCHMARK] + SECTORS + PAIR_MEMBERS))
PERIOD = "15y"
MIN_HISTORY = 252 * 3  # drop tickers with < 3y of data
SIG_FIGS = 4  # price rounding to keep the file small

OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "prices.js")


def _round_sig(x, sig=SIG_FIGS):
    """Round to ``sig`` significant figures (vectorised, scalar-decimals safe)."""
    x = np.asarray(x, dtype=float)
    out = np.array(x)
    nz = x != 0
    scale = np.power(10.0, sig - 1 - np.floor(np.log10(np.abs(x[nz]))))
    out[nz] = np.round(x[nz] * scale) / scale
    return out


def main():
    print(f"Fetching {len(TICKERS)} tickers ({PERIOD} daily)...")
    raw = yf.download(TICKERS, period=PERIOD, auto_adjust=False,
                      group_by="ticker", progress=False, threads=True)

    # Build a per-series frame of [open, high, low, close, adj_close, volume]
    frames = {}
    for tk in TICKERS:
        try:
            df = raw[tk].dropna(how="all")
        except KeyError:
            print(f"  ! {tk}: not returned, skipping")
            continue
        df = df.rename(columns={
            "Open": "open", "High": "high", "Low": "low",
            "Close": "close", "Adj Close": "adj_close", "Volume": "volume"})
        cols = ["open", "high", "low", "close", "adj_close", "volume"]
        df = df[cols].dropna()
        if len(df) < MIN_HISTORY:
            print(f"  ! {tk}: only {len(df)} rows (< {MIN_HISTORY}), skipping")
            continue
        frames[tk] = df

    # Align all series on a common trading-day index (inner join), small ffill
    common = None
    for df in frames.values():
        common = df.index if common is None else common.intersection(df.index)
    common = common.sort_values()
    print(f"Common trading days: {len(common)} "
          f"({common[0].date()} to {common[-1].date()})")

    kept = sorted(frames)
    data = {}
    for tk in kept:
        df = frames[tk].reindex(common).ffill(limit=3).dropna()
        # reindex again so every ticker has identical length T after the ffill/dropna
        df = df.reindex(common).ffill(limit=3)
        data[tk] = {
            "open": _round_sig(df["open"].to_numpy()).tolist(),
            "high": _round_sig(df["high"].to_numpy()).tolist(),
            "low": _round_sig(df["low"].to_numpy()).tolist(),
            "close": _round_sig(df["close"].to_numpy()).tolist(),
            "adj_close": _round_sig(df["adj_close"].to_numpy()).tolist(),
            "volume": df["volume"].fillna(0).astype("int64").tolist(),
        }

    pairs = [p for p in PAIRS if p[0] in kept and p[1] in kept]
    out = {
        "meta": {
            "start": str(common[0].date()),
            "end": str(common[-1].date()),
            "source": "yfinance",
            "adjusted": True,
            "n_days": len(common),
        },
        "dates": [d.strftime("%Y-%m-%d") for d in common],
        "tickers": kept,
        "pairs": pairs,
        "data": data,
    }

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by stb-project/fetch_data.py -- do not edit by hand.\n")
        f.write("const DATA_PRICES = ")
        json.dump(out, f, separators=(",", ":"), ensure_ascii=True)
        f.write(";\n")
    size_kb = os.path.getsize(OUT_PATH) / 1024
    print(f"Wrote {OUT_PATH} ({size_kb:.0f} KB) -- {len(kept)} tickers, "
          f"{len(pairs)} pairs, {len(common)} days.")


if __name__ == "__main__":
    main()
