connections = open("connectionroutes.txt", "r")
newconnections = open("newconnectionroutes.txt", "w")

lines = connections.read()

lines = lines.replace(" ", "\t")
lines = lines.replace("SaultStMarie", "Sault St. Marie")
lines = lines.replace("NewYork", "New York")
lines = lines.replace("SaltLakeCity", "Salt Lake City")
lines = lines.replace("LosAngeles", "Los Angeles")
lines = lines.replace("SanFrancisco", "San Francisco")
lines = lines.replace("LasVegas", "Las Vegas")
lines = lines.replace("SantaFe", "Santa Fe")
lines = lines.replace("ElPaso", "El Paso")
lines = lines.replace("OklahomaCity", "Oklahoma City")
lines = lines.replace("KansasCity", "Kansas City")
lines = lines.replace("LittleRock", "Little Rock")
lines = lines.replace("NewOrleans", "New Orleans")
lines = lines.replace("SaintLouis", "Saint Louis")
lines = lines.replace("purple", "pink")
lines = lines.replace("rainbow", "gray")
newconnections.write(lines)

connections.close()
newconnections.close()